### ISSUE TITLE
CSS Broke after Chrome Update?

### ISSUE THREAD

**Issue by RCL-Loren** [trilogy-group/cn-wspro-client-releases#2]
After a recent Chrome update, the canvas on the widget is not rendering correctly so that the contents can't be seen as in the following screenshot:

![image](https://user-images.githubusercontent.com/15079039/119811450-18d67d00-beb5-11eb-973a-f26d7b71114f.png)

However, if the root element CSS is modified to disable Height:100% the elements can be seen:

![image](https://user-images.githubusercontent.com/15079039/119811862-8a163000-beb5-11eb-90a6-4df3fe2ce16d.png)

This is on Windows 10 Build 19042.985 / Windows Feature Experience Pack 120.2212.2020.0 / Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by ashishbedicn** [comment]
Thank you very much for you valuable inputs, @RCL-Loren and @chulayuth-devfactory. New version of this extension, which fixes the empty screen problem is released. It can be downloaded from the same repository: https://github.com/trilogy-group/cn-wspro-client-releases

You shall remove the old version and install the new version.
